version: "3.7"

networks:
    local:

services:
    nginx:
        container_name: nginx
        image: nginx:stable
        ports:
            - 81:80
        volumes:
            - ./app:/var/www/html
            - ./nginx/log:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - local
        depends_on:
            - php
            - mysql
    php:
        image: herdanis/php7.3-composer-laravel
        container_name: php
        volumes:
            - ./app:/var/www/html
        networks:
            - local
        restart: unless-stopped
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        # ports:
        #     - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        command: --max_allowed_packet=32505856
        environment:
            MYSQL_DATABASE: baseData
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - local
    myadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 82:80
        networks:
            - local
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
